name             'webserver-ajunior'
maintainer       'ajunior'
maintainer_email 'ajunior@avenuecode.com'
description      'Chef Training Practice'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

# depends 'chef-locale'
depends 'git'
depends 'curl'
depends 'apache2'
depends 'mysql'
depends 'nodejs'
# depends 'zlib'
# depends 'java'
# depends 'mysql'
# depends 'postgresql'
# depends 'redis_2_cookbook'
# depends 'imagemagick'
# depends 'mongodb'
# depends 'elasticsearch'
# depends 'nodejs'
# depends 'rvm'
# depends 'user'
# depends 'zsh'
# depends 'lxmx_oh_my_zsh'